### ISSUE TITLE
Bug: Delete behaviour between Features and Step Definitions

### ISSUE THREAD

**Issue by edstewart** [TradeMe/tractor#72] opened 2016-06-21 22:19 UTC
Deleting a step in the Step Definitions view does not delete it within the Features view, and vice versa.

**Comment by ghost** [comment] 2016-06-28 02:17
By design
The definition may be used by another feature, and vice versa

We do want to add usage tracking later

Going to close this for now

**Closed as completed** 2016-06-28 02:18 UTC
